#include <std_include.hpp>

#ifdef DEBUG
#include "loader/component_loader.hpp"

#include "game/game.hpp"
#include "game/dvars.hpp"

#include "component/scheduler.hpp"
#include "component/command.hpp"
#include "component/fastfiles.hpp"
#include "../gui.hpp"
#include "../asset_list.hpp"

#include <utils/string.hpp>
#include <utils/hook.hpp>

namespace gui::asset_list::techet
{
	namespace
	{
		std::array<const char*, game::TECHNIQUE_COUNT> technique_names = 
		{
			"TECHNIQUE_ZPREPASS",
			"TECHNIQUE_ZPREPASS_VELOCITY_RIGID",
			"TECHNIQUE_ZPREPASS_VELOCITY_SKINNED",
			"TECHNIQUE_ZPREPASS_HIDIR",
			"TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_RIGID",
			"TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_SKINNED",
			"TECHNIQUE_BUILD_SHADOWMAP_DEPTH",
			"TECHNIQUE_BUILD_SHADOWMAP_COLOR",
			"TECHNIQUE_UNLIT",
			"TECHNIQUE_EMISSIVE",
			"TECHNIQUE_EMISSIVE_DFOG",
			"TECHNIQUE_EMISSIVE_SHADOW",
			"TECHNIQUE_EMISSIVE_SHADOW_DFOG",
			"TECHNIQUE_LIT",
			"TECHNIQUE_LIT_DIR",
			"TECHNIQUE_LIT_DIR_SHADOW",
			"TECHNIQUE_LIT_SPOT",
			"TECHNIQUE_LIT_SPOT_SHADOW",
			"TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_LIT_OMNI",
			"TECHNIQUE_LIT_OMNI_SHADOW",
			"TECHNIQUE_LIT_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_LIT_DYNAMIC_BRANCHING",
			"TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING",
			"TECHNIQUE_LIT_DFOG",
			"TECHNIQUE_LIT_DIR_DFOG",
			"TECHNIQUE_LIT_DIR_SHADOW_DFOG",
			"TECHNIQUE_LIT_SPOT_DFOG",
			"TECHNIQUE_LIT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_LIT_OMNI_DFOG",
			"TECHNIQUE_LIT_OMNI_SHADOW_DFOG",
			"TECHNIQUE_LIT_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_LIT_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_LIGHT_SPOT",
			"TECHNIQUE_LIGHT_OMNI",
			"TECHNIQUE_LIGHT_SPOT_SHADOW",
			"TECHNIQUE_LIGHT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_LIGHT_SPOT_STENCIL",
			"TECHNIQUE_LIGHT_OMNI_STENCIL",
			"TECHNIQUE_LIGHT_SPOT_DFOG",
			"TECHNIQUE_LIGHT_OMNI_DFOG",
			"TECHNIQUE_LIGHT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_LIGHT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_LIGHT_SPOT_STENCIL_DFOG",
			"TECHNIQUE_LIGHT_OMNI_STENCIL_DFOG",
			"TECHNIQUE_FAKELIGHT_NORMAL",
			"TECHNIQUE_FAKELIGHT_VIEW",
			"TECHNIQUE_SUNLIGHT_PREVIEW",
			"TECHNIQUE_CASE_TEXTURE",
			"TECHNIQUE_WIREFRAME_SOLID",
			"TECHNIQUE_WIREFRAME_SHADED",
			"TECHNIQUE_THERMAL",
			"TECHNIQUE_CTQ",
			"TECHNIQUE_VELOCITY_RIGID",
			"TECHNIQUE_VELOCITY_SKINNED",
			"TECHNIQUE_DEBUG_BUMPMAP",
			"TECHNIQUE_INSTANCED_ZPREPASS",
			"TECHNIQUE_INSTANCED_ZPREPASS_VELOCITY_RIGID",
			"TECHNIQUE_INSTANCED_ZPREPASS_VELOCITY_SKINNED",
			"TECHNIQUE_INSTANCED_ZPREPASS_HIDIR",
			"TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_RIGID",
			"TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_SKINNED",
			"TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_DEPTH",
			"TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_COLOR",
			"TECHNIQUE_INSTANCED_UNLIT",
			"TECHNIQUE_INSTANCED_EMISSIVE",
			"TECHNIQUE_INSTANCED_EMISSIVE_DFOG",
			"TECHNIQUE_INSTANCED_EMISSIVE_SHADOW",
			"TECHNIQUE_INSTANCED_EMISSIVE_SHADOW_DFOG",
			"TECHNIQUE_INSTANCED_LIT",
			"TECHNIQUE_INSTANCED_LIT_DIR",
			"TECHNIQUE_INSTANCED_LIT_DIR_SHADOW",
			"TECHNIQUE_INSTANCED_LIT_SPOT",
			"TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW",
			"TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_INSTANCED_LIT_OMNI",
			"TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW",
			"TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING",
			"TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING",
			"TECHNIQUE_INSTANCED_LIT_DFOG",
			"TECHNIQUE_INSTANCED_LIT_DIR_DFOG",
			"TECHNIQUE_INSTANCED_LIT_DIR_SHADOW_DFOG",
			"TECHNIQUE_INSTANCED_LIT_SPOT_DFOG",
			"TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_INSTANCED_LIT_OMNI_DFOG",
			"TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW_DFOG",
			"TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT",
			"TECHNIQUE_INSTANCED_LIGHT_OMNI",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_STENCIL",
			"TECHNIQUE_INSTANCED_LIGHT_OMNI_STENCIL",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_OMNI_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_SPOT_STENCIL_DFOG",
			"TECHNIQUE_INSTANCED_LIGHT_OMNI_STENCIL_DFOG",
			"TECHNIQUE_INSTANCED_FAKELIGHT_NORMAL",
			"TECHNIQUE_INSTANCED_FAKELIGHT_VIEW",
			"TECHNIQUE_INSTANCED_SUNLIGHT_PREVIEW",
			"TECHNIQUE_INSTANCED_CASE_TEXTURE",
			"TECHNIQUE_INSTANCED_WIREFRAME_SOLID",
			"TECHNIQUE_INSTANCED_WIREFRAME_SHADED",
			"TECHNIQUE_INSTANCED_THERMAL",
			"TECHNIQUE_INSTANCED_CTQ",
			"TECHNIQUE_INSTANCED_VELOCITY_RIGID",
			"TECHNIQUE_INSTANCED_VELOCITY_SKINNED",
			"TECHNIQUE_INSTANCED_DEBUG_BUMPMAP",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS_VELOCITY_RIGID",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS_VELOCITY_SKINNED",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_RIGID",
			"TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_SKINNED",
			"TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_DEPTH",
			"TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_COLOR",
			"TECHNIQUE_SUBDIV_PATCH_UNLIT",
			"TECHNIQUE_SUBDIV_PATCH_EMISSIVE",
			"TECHNIQUE_SUBDIV_PATCH_EMISSIVE_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW",
			"TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DIR",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_SUBDIV_PATCH_LIT_OMNI",
			"TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DIR_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_STENCIL",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI_STENCIL",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_STENCIL_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI_STENCIL_DFOG",
			"TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_NORMAL",
			"TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_VIEW",
			"TECHNIQUE_SUBDIV_PATCH_SUNLIGHT_PREVIEW",
			"TECHNIQUE_SUBDIV_PATCH_CASE_TEXTURE",
			"TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SOLID",
			"TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SHADED",
			"TECHNIQUE_SUBDIV_PATCH_THERMAL",
			"TECHNIQUE_SUBDIV_PATCH_CTQ",
			"TECHNIQUE_SUBDIV_PATCH_VELOCITY_RIGID",
			"TECHNIQUE_SUBDIV_PATCH_VELOCITY_SKINNED",
			"TECHNIQUE_SUBDIV_PATCH_DEBUG_BUMPMAP",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_VELOCITY_RIGID",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_VELOCITY_SKINNED",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_RIGID",
			"TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_SKINNED",
			"TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_DEPTH",
			"TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_COLOR",
			"TECHNIQUE_NO_DISPLACEMENT_UNLIT",
			"TECHNIQUE_NO_DISPLACEMENT_EMISSIVE",
			"TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW",
			"TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DIR",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW_CUCOLORIS",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_STENCIL",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI_STENCIL",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW_CUCOLORIS_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_STENCIL_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI_STENCIL_DFOG",
			"TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_NORMAL",
			"TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_VIEW",
			"TECHNIQUE_NO_DISPLACEMENT_SUNLIGHT_PREVIEW",
			"TECHNIQUE_NO_DISPLACEMENT_CASE_TEXTURE",
			"TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SOLID",
			"TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SHADED",
			"TECHNIQUE_NO_DISPLACEMENT_THERMAL",
			"TECHNIQUE_NO_DISPLACEMENT_CTQ",
			"TECHNIQUE_NO_DISPLACEMENT_VELOCITY_RIGID",
			"TECHNIQUE_NO_DISPLACEMENT_VELOCITY_SKINNED",
			"TECHNIQUE_NO_DISPLACEMENT_DEBUG_BUMPMAP"
		};

		std::array<const char*, game::MTL_ARG_COUNT> material_arg_type_names =
		{
			"CODE_CONST",
			"CODE_TEXTURE",
			"CODE_SAMPLER",
			"MATERIAL_CONST",
			"LITERAL_CONST",
			"MATERIAL_TEXTURE",
			"MATERIAL_SAMPLER",
		};

		void draw_technique(game::MaterialTechnique* technique)
		{
#define DRAW_SUB_ASSET_PROPERTY_NAME(__var__, __fmt__, __name__) \
				ImGui::Text(#__name__ ": " __fmt__, __var__->__name__ != nullptr ? __var__->__name__->name : "null"); \

#define DRAW_SUB_ASSET_PROPERTY_NAME_COPY(__var__, __fmt__, __name__) \
				ImGui::Text(#__name__ ": " __fmt__, __var__->__name__ != nullptr ? __var__->__name__->name : "null"); \

#define DRAW_SUB_ASSET_PROPERTY(__var__, __fmt__, __name__) \
				ImGui::Text(#__name__ ": " __fmt__, __var__->__name__); \

			if (ImGui::Button(technique->hdr.name))
			{
				gui::copy_to_clipboard(technique->hdr.name);
			}

			for (auto o = 0; o < technique->hdr.passCount; o++)
			{
				const auto pass = &technique->passArray[o];

				if (ImGui::TreeNode(pass, "pass %i", o))
				{
					DRAW_SUB_ASSET_PROPERTY_NAME(pass, "%s", vertexShader);
					DRAW_SUB_ASSET_PROPERTY_NAME(pass, "%s", vertexDecl);
					DRAW_SUB_ASSET_PROPERTY_NAME(pass, "%s", hullShader);
					DRAW_SUB_ASSET_PROPERTY_NAME(pass, "%s", domainShader);
					DRAW_SUB_ASSET_PROPERTY_NAME(pass, "%s", pixelShader);

					ImGui::NewLine();

					DRAW_SUB_ASSET_PROPERTY(pass, "%i", pixelOutputMask);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", perPrimArgCount);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", perObjArgCount);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", stableArgCount);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", perPrimArgSize);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", perObjArgSize);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", stableArgSize);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", customBufferFlags);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", customSamplerFlags);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", precompiledIndex);
					DRAW_SUB_ASSET_PROPERTY(pass, "%i", stageConfig);

					auto id = 0;
					const auto draw_arg = [&](game::MaterialShaderArgument* arg, const std::uint32_t arg_index)
					{
						ImGui::SetNextItemOpen(true, ImGuiCond_FirstUseEver);

						ImGui::PushID(id++);
						if (ImGui::TreeNode(arg, "argument %i", arg_index))
						{
							ImGui::Text("type: %s", material_arg_type_names[arg->type]);

							DRAW_SUB_ASSET_PROPERTY(arg, "%i", shader);
							DRAW_SUB_ASSET_PROPERTY(arg, "%i", dest);

							switch (arg->type)
							{
							case game::MTL_ARG_CODE_CONST:
								ImGui::InputScalarN("codeConst.index", ImGuiDataType_U16, &arg->u.codeConst.index, 1, NULL, NULL, "%d");
								ImGui::InputScalarN("codeConst.firstRow", ImGuiDataType_U8, &arg->u.codeConst.firstRow, 1, NULL, NULL, "%d");
								ImGui::InputScalarN("codeConst.rowCount", ImGuiDataType_U8, &arg->u.codeConst.rowCount, 1, NULL, NULL, "%d");
								break;
							case game::MTL_ARG_MATERIAL_CONST:
								ImGui::InputScalarN("nameHash", ImGuiDataType_U32, &arg->u.nameHash, 1, NULL, NULL, "%u");
								break;
							case game::MTL_ARG_LITERAL_CONST:
								ImGui::DragFloat4("literal", arg->u.literalConst);
								break;
							case game::MTL_ARG_MATERIAL_TEXTURE:
							case game::MTL_ARG_MATERIAL_SAMPLER:
							case game::MTL_ARG_CODE_TEXTURE:
							case game::MTL_ARG_CODE_SAMPLER:
								ImGui::Text("codeSampler: %u", arg->u.codeSampler);
								break;
							}

							ImGui::TreePop();
						}

						ImGui::PopID();
					};


					if (ImGui::TreeNode("per primitive args"))
					{
						for (auto arg_index = 0u; arg_index < pass->perPrimArgCount; arg_index++)
						{
							const auto arg = &pass->args[arg_index];
							draw_arg(arg, arg_index);
						}

						ImGui::TreePop();
					}

					ImGui::Separator();

					if (ImGui::TreeNode("per object args"))
					{
						for (auto arg_index = 0u; arg_index < pass->perObjArgCount; arg_index++)
						{
							const auto arg = &pass->args[pass->perPrimArgCount + arg_index];
							draw_arg(arg, arg_index);
						}

						ImGui::TreePop();
					}

					ImGui::Separator();

					if (ImGui::TreeNode("stable args"))
					{
						for (auto arg_index = 0u; arg_index < pass->stableArgCount; arg_index++)
						{
							const auto arg = &pass->args[pass->perPrimArgCount + pass->perObjArgCount + arg_index];
							draw_arg(arg, arg_index);
						}

						ImGui::TreePop();
					}

					ImGui::TreePop();
				}
			}
		}

		bool draw_techset_window(game::MaterialTechniqueSet* asset)
		{
			ImGui::SetNextItemOpen(true, ImGuiCond_FirstUseEver);

#define DRAW_ASSET_PROPERTY_INPUT_U8(__name__) \
				InputU8(#__name__, &asset->__name__); \

#define DRAW_ASSET_PROPERTY_INPUT_S32(__name__) \
				ImGui::InputInt(#__name__, &asset->__name__); \

#define DRAW_ASSET_PROPERTY(__name__, __fmt__) \
				ImGui::Text(#__name__ ": " __fmt__, asset->__name__); \

#define DRAW_ASSET_PROPERTY_COPY(__name__) \
				ImGui::Text(#__name__ ": "); \
				ImGui::SameLine(); \
				if (ImGui::Button(asset->__name__)) \
				{ \
					gui::copy_to_clipboard(asset->__name__); \
				} \

			DRAW_ASSET_PROPERTY_COPY(name);
			DRAW_ASSET_PROPERTY(flags, "%i");
			DRAW_ASSET_PROPERTY(worldVertFormat, "%i");
			DRAW_ASSET_PROPERTY(preDisplacementOnlyCount, "%i");

			static std::uint32_t inputs[game::TECHNIQUE_COUNT]{};

			for (auto i = 0; i < game::TECHNIQUE_COUNT; i++)
			{
				const auto technique = asset->techniques[i];

				if (ImGui::TreeNode(technique_names[i], "%s %s", technique_names[i], technique == nullptr ? "(null)" : ""))
				{
					ImGui::InputScalarN("technique index", ImGuiDataType_U32, &inputs[i], 1);

					ImGui::SameLine();

					if (ImGui::Button("copy technique") && inputs[i] < game::TECHNIQUE_COUNT)
					{
						asset->techniques[i] = asset->techniques[inputs[i]];
					}

					if (technique != nullptr)
					{
						draw_technique(technique);
					}

					ImGui::TreePop();
				}
			}

			ImGui::Separator();

			return true;
		}
	}

	class component final : public component_interface
	{
	public:
		void post_unpack() override
		{
			gui::asset_list::add_asset_view<game::MaterialTechniqueSet>(game::ASSET_TYPE_TECHNIQUE_SET, draw_techset_window);
		}
	};
}

REGISTER_COMPONENT(gui::asset_list::techet::component)
#endif
